### ISSUE TITLE
Season 4 has 2 part ? or will it end in ep16 ?

### ISSUE THREAD

**Issue by sadeghbarati** [egoist/aot-next-episode#1]
I'm not a _**`Manga Reader`**_ so I came up with this question 😄

**Comment by egoist** [comment]
Likely it'll get a part 2 or a movie since 16 episodes can only cover up to 121 chapters, while it has 139 chapters in total.

**Comment by egoist** [comment]
Closing.

btw rumor suggests part 2 will only have 12 episodes, which won't be enough to cover the manga, be prepared for a part 3 or a movie 😂
